[workspace]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
authors = ["m1m1sha"]
repository = "https://github.com/m1m1sha/wib-rs"

[workspace.dependencies]

[package]
name = "wib-rs"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
